# Generated by Django 4.0.2 on 2022-02-21 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('impression', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression',
            name='pattern4',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], blank=True, null=True,verbose_name='パターン４'),
            preserve_default=False,
        ),
    ]
